### ISSUE TITLE
Add support for cluster by in Snowflake

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#1027]
Proposed API:

```
config {
  type: "table",
  snowflake: {
    clusterBy: ["field1", "field2"]
  }
}
```

https://docs.snowflake.com/en/sql-reference/sql/create-table.html

**Comment by rumbin** [comment]
The definition of an explicit clustering key serves two purposes. First and obviously, the clustering key should be specified right on table creation, in order to not cause compute costs that would occur when clustering the table after creation. Secondly, like discussed in the DBT thread, the clustering key may also be employed as an additional matching criterion in the MERGE operation, in order to increase join/merge performance.

**Comment by rumbin** [comment]
see also: https://github.com/fishtown-analytics/dbt/issues/2139
