### ISSUE TITLE
Enable Stored Procedure Config Type for Enterprise Scheduling

### ISSUE THREAD

**Issue by Anthony-Savio** [dataform-co/dataform#1151]
Enable scheduling capabilities for execution of stored procedures ( Or Custom SQL statements which invoke the stored procedure) with dependencies between different executions. 

Example: Stored Procedure for ETL operations within BigQuery 

Step 1: Call stored_proc( SourceTable1, TargetTable1);
Step 2: Call stored_proc(TargetTable1, TargetTable2) ; -- Dependent on successful execution of Step 1

**Comment by Ekrekr** [comment]
I'm closing this issue for now because I think it's effectively against the Dataform paradigm - please give an example if it's not!

Reasoning:
* Stored procedures are used to re-use SQL code, for re-applying it in a loop or across code, for example applying it to each row of a table.
* This loses the benefits of a hermetically generated compiled graph, instead relying on stored state in BigQuery.
* The same can be accomplished by using the SQL templating that Dataform provides.
* Dataform already has dependencies on successful execution of actions, and I don't think there's a use case here that we wouldn't support - just not with the stored procedure paradigm.
