### ISSUE TITLE
Dry run flag for BigQuery assets

### ISSUE THREAD

**Issue by mschaszberger** [dataform-co/dataform#1242]
Currently, the --dry-run flag in Dataform shows users the final SQL that Dataform will run on your warehouse without actually running it. It would be useful to have a similar dry run flag, but for BigQuery queries, so users can emulate a dry run in BigQuery from Dataform. 

References
[1] https://docs.dataform.co/dataform-cli#run-your-code
[2] https://cloud.google.com/bigquery/docs/dry-run-queries

**Comment by xaptronic** [comment]
I did not find that `--dry-run` shows any SQL that will be run - it only says what actions it is going to take. Is there something I'm missing about what "show SQL" means?

**Comment by Ekrekr** [comment]
Thanks for the suggestion! I've added doing a [dry run](https://cloud.google.com/bigquery/docs/running-queries#dry-run) against bigquery as an extra step here, because it often gives useful error details and it is a free API call.

If you want to see the SQL that will be run in more detail, the `--json` option is what you're looking for.
