### ISSUE TITLE
protected in config is always true

### ISSUE THREAD

**Issue by dali-rmw** [dataform-co/dataform#1608]
Hello, 
Setting "protected: false" is ignored, and it consistently behaves as if it were true.
<img width="234" alt="image" src="https://github.com/dataform-co/dataform/assets/107106384/6126bf4b-cdfe-4ae7-b2e2-4a674da52b92">

<img width="301" alt="image" src="https://github.com/dataform-co/dataform/assets/107106384/ab5b5e2a-e6d5-479f-9468-47dce2bebf7b">

**Comment by BenBirt** [comment]
Thanks for filing this issue.

Just to be clear - it looks like `protected: false` is only ignored in the part of the framework which performs config block validation (https://github.com/dataform-co/dataform/blob/main/core/session.ts#L142).

Obviously the trivial workaround is to simply remove the line - because this is the default.

However, we should definitely fix this! We should probably just replace `sqlxConfig.hasOwnProperty("protected")` with `sqlxConfig.protected`.

**Comment by dali-rmw** [comment]
Hello, 
thank you for your reply. I understand that it's initially set to false by default. However, for my specific scenario, I need to dynamically set it using JavaScript.

**Comment by BenBirt** [comment]
Okay, makes sense. In that case I would either:
1) Not use SQLX (and thus avoid this check), i.e. use JavaScript entirely
2) Send us a PR to do the suggestion above (I'd be happy to then immediately publish that change in a new `@dataform/core` version)
