### ISSUE TITLE
materialized views create error

### ISSUE THREAD

**Issue by arjitshu** [dataform-co/dataform#1640]
I have created new MV with below dataform code but facing issue while execution of the file.
Although MV created successfully but workflow execution logs  showing an error.

```
config {
   type: "view",
   materialized: true,
   name: "orders_count_by_gender",
   tags: ["orders_count_by_gender"],
   schema: dataform.projectConfig.vars.goldSchema,
   tags: ["orders_count_by_gender" ,"gold"],
   columns: {
       gender: "gender male or female",
       gender_count: "gender count"
   },
   bigquery: {
       additionalOptions: {
           refresh_interval_minutes: "10"
       },
       labels: {
           "type": "reporting"
       }
   }
}
SELECT gender, count(*) as gender_count
FROM ${ref("fact_orders")}
group by gender

```

**Error** 

Error message Error: googleapi: Error 400: Schema update for materialized views is not supported., invalid
SQL code change did not involved actual schema changes

<img width="1244" alt="Screenshot 2024-01-08 at 13 17 31" src="https://github.com/dataform-co/dataform/assets/129896413/9758b3f2-d1d3-4249-9329-d0e5f2f42b98">

**Comment by BenBirt** [comment]
Thanks for filing this issue. I think it's happening because of your `columns: ...` section in the `config` block, which Dataform interprets as a table metadata update BigQuery method call - and this is apparently invalid for materialized views.

I have filed an internal issue to make Dataform stop doing this, but for now if you'd like a workaround I would suggest removing `columns: ...`.

**Comment by Ekrekr** [comment]
Tracked in b/296281345
