### ISSUE TITLE
run_query(SQL) in js custom function (& get results)

### ISSUE THREAD

**Issue by AntoineGiraud** [dataform-co/dataform#1667]
Hi,

Could it be possible to execute SQL on the DB & get the results in my custom js function ?

`results = run_query('select 1 as id')`

for instance, i'd like to fetch the columns of a given table
in order to make a custom query based on the fields of that table !

```js
let sql = "SELECT column_name, data_type, description
            FROM `demo_scd2.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS`
            where table_name='demo_scd2'";
let columns = run_query(sql);
```

use case : SCD2 function with custom behaviour, not included in the existing [dataform-scd](https://github.com/dataform-co/dataform-scd)

Thanks in advance for your interest :)

Antoine

PS: basicly ... like [dbt's run_query](https://docs.getdbt.com/reference/dbt-jinja-functions/run_query) in a macro ...

**Comment by BenBirt** [comment]
Dataform does not support this (by design).

Dataform executes your JavaScript (and SQLX) - an operation we call "compilation" - in a sandbox, i.e. that code has no (direct) filesystem access, and no networking access.

We do this for two reasons:
1) We want to ensure that compilation is _hermetic_: if you compile the same code, you should get the same result. If that code is allowed to depend on the external world, hermeticity is broken. Hermeticity is a valuable property, for various reasons, but some of the most important are: reproducibility, auditability, and debuggability.
2) We want to ensure that compilation is _fast_: if your code can depend on the state of the data (and it can have loops, functions, whatever), then it could take tens of seconds, or even minutes, to compile. We want to ensure that we can present the compiled result of your code to you within single-digit (or low double-digit) seconds, always.

All that said: I'd encourage any readers of this to check out BigQuery scripting, using which you can do many dynamic things, including dynamically building queries as a result of other queries.

**Comment by AntoineGiraud** [comment]
Thanks a lot for the quick response, the clear explanation & potential option on [BigQuery scripting](https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language) ! 🙏
