### ISSUE TITLE
[Dataform][CLI] - dataform install still looks for package.json even when workflow-settings.yaml is available.

### ISSUE THREAD

**Issue by Murli16** [dataform-co/dataform#1749]
With dataform CLI version - **3.0.0-beta.5**

The dataform repo consists of the below folder structure
defintions/
workflow_settings.yaml --> This is the new feature introduced to combine dataform.json and package.json I believe 

dataform install command returns the below error.

(node:278) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Dataform encountered an error: Package installation is only supported when specifying @dataform/core version in 'package.json'
**Error: Package installation is only supported when specifying @dataform/core version in 'package.json'**

For now , I have fixed by removing the core version from workflow_settings.yaml and adding package.json.

Could you please let us know if this is a bug ?

**Comment by Ekrekr** [comment]
This works as intented - the error message is just a bit confusing.

When using `workflow_settings.yaml`, you never need to run `dataform install`. Packages are installed at runtime, in a temporary directory. You never see the node_modules file!

Fixed in https://github.com/dataform-co/dataform/pull/1795
