### ISSUE TITLE
double quotes throwing errors in sqlx files

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform#265]
---
Moved from dataform-co/dataform-co#854
/cc @dwl285

**Comment by dwl285** [comment]
@benoitfayolle for tracking

**Comment by BenBirt** [comment]
After a bit of investigation...

It turns out that PostgresSQL and Snowflake SQL reserve the use of `"doubly_quoted_strings"` as identifiers (https://docs.snowflake.net/manuals/sql-reference/identifiers-syntax.html, https://www.postgresql.org/docs/9.1/sql-syntax-lexical.html).

So this error was actually Redshift/Postgres/Snowflake complaining that the relevant query(s) were referencing an invalid identifier name correctly.

Thus, closing as there's no bug to fix here, it's up to the SQL variant belonging to the user's choice of warehouse.
