### ISSUE TITLE
IDE support (not DataForm IDE) for .sqlx files

### ISSUE THREAD

**Issue by dorzey** [dataform-co/dataform#461]
Is there any planned support for .sqlx files in say vscode or atom?

**Comment by BenBirt** [comment]
Hi @dorzey, thanks for the interest!

Since our IDE is based on monaco (open source vscode), we can fairly easily bring the same level of syntax highlighting etc into vscode.

Formatting is a little harder as that code is wired into `@dataform/api`; that said we should be able to disentangle it and pull it into some API more native to vscode.

In any case, we'll be sure to add this to our roadmap!

**Comment by darrenhaken** [comment]
Thanks, @BenBirt - any idea on ETA for these kinds of features?

**Comment by christophepas** [comment]
I'd love to have this!

**Comment by GJMcGowan** [comment]
Hi everyone, we've released an alpha of a [vscode extension](https://marketplace.visualstudio.com/items?itemName=dataform.dataform) including the following features:

- Syntax highlighting for .sqlx files
- Realtime compilation of your project
- cmd + click on a ref() function to go to the file that it references

Let us know what you think of it!

**Comment by faaez** [comment]
Thanks for your work on the vscode extension! Are there plans to add formatting support to the extension as well?

**Comment by Ekrekr** [comment]
We're considering doing this, potentially via SQLFluff!

Closing this bug however, as it's for the IDE support which does exist (though needs some maintenance).
